/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QaRouteImport } from './routes/qa'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FixRouteImport } from './routes/fix'
import { Route as DataConsistencyRouteImport } from './routes/data-consistency'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowIndexRouteImport } from './routes/workflow.index'
import { Route as WorkflowIdRouteImport } from './routes/workflow.$id'
import { Route as InviteAcceptRouteImport } from './routes/invite.accept'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QaRoute = QaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FixRoute = FixRouteImport.update({
  id: '/fix',
  path: '/fix',
  getParentRoute: () => rootRouteImport,
} as any)
const DataConsistencyRoute = DataConsistencyRouteImport.update({
  id: '/data-consistency',
  path: '/data-consistency',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIndexRoute = WorkflowIndexRouteImport.update({
  id: '/workflow/',
  path: '/workflow/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/data-consistency': typeof DataConsistencyRoute
  '/fix': typeof FixRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handoff': typeof HandoffRoute
  '/integrations': typeof IntegrationsRoute
  '/lifecycle': typeof LifecycleRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/qa': typeof QaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/workflow/': typeof WorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/data-consistency': typeof DataConsistencyRoute
  '/fix': typeof FixRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handoff': typeof HandoffRoute
  '/integrations': typeof IntegrationsRoute
  '/lifecycle': typeof LifecycleRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/qa': typeof QaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/workflow': typeof WorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/data-consistency': typeof DataConsistencyRoute
  '/fix': typeof FixRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/handoff': typeof HandoffRoute
  '/integrations': typeof IntegrationsRoute
  '/lifecycle': typeof LifecycleRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/qa': typeof QaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/workflow/': typeof WorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/data-consistency'
    | '/fix'
    | '/forgot-password'
    | '/handoff'
    | '/integrations'
    | '/lifecycle'
    | '/onboarding'
    | '/opportunities'
    | '/qa'
    | '/reset-password'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/verify-email'
    | '/invite/accept'
    | '/workflow/$id'
    | '/workflow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/data-consistency'
    | '/fix'
    | '/forgot-password'
    | '/handoff'
    | '/integrations'
    | '/lifecycle'
    | '/onboarding'
    | '/opportunities'
    | '/qa'
    | '/reset-password'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/verify-email'
    | '/invite/accept'
    | '/workflow/$id'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/dashboard'
    | '/data-consistency'
    | '/fix'
    | '/forgot-password'
    | '/handoff'
    | '/integrations'
    | '/lifecycle'
    | '/onboarding'
    | '/opportunities'
    | '/qa'
    | '/reset-password'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/verify-email'
    | '/invite/accept'
    | '/workflow/$id'
    | '/workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DashboardRoute: typeof DashboardRoute
  DataConsistencyRoute: typeof DataConsistencyRoute
  FixRoute: typeof FixRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HandoffRoute: typeof HandoffRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LifecycleRoute: typeof LifecycleRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  QaRoute: typeof QaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  WorkflowIdRoute: typeof WorkflowIdRoute
  WorkflowIndexRoute: typeof WorkflowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa': {
      id: '/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof QaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fix': {
      id: '/fix'
      path: '/fix'
      fullPath: '/fix'
      preLoaderRoute: typeof FixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-consistency': {
      id: '/data-consistency'
      path: '/data-consistency'
      fullPath: '/data-consistency'
      preLoaderRoute: typeof DataConsistencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/': {
      id: '/workflow/'
      path: '/workflow'
      fullPath: '/workflow/'
      preLoaderRoute: typeof WorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DashboardRoute: DashboardRoute,
  DataConsistencyRoute: DataConsistencyRoute,
  FixRoute: FixRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HandoffRoute: HandoffRoute,
  IntegrationsRoute: IntegrationsRoute,
  LifecycleRoute: LifecycleRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  QaRoute: QaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  WorkflowIdRoute: WorkflowIdRoute,
  WorkflowIndexRoute: WorkflowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
